# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm i --force
    - run: npm run build --if-present
    - name: PM2 INSTALL
      run: npm i pm2@latest -g
    
    - name: Login to Docker hub
      uses: docker/login-action@v3
      with:
           username: ${{ secrets.USERNAME }}
           password: ${{ secrets.TOKEN }}
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3


    - name: Build and push
      uses: docker/build-push-action@v5
      with:
             context: .
             file: ./Dockerfile
             push: true
             tags: ${{ secrets.USERNAME }}/docker_ga:latest
    - name: Starting Docker
      uses: actions/checkout@v3
    - name: Create dockerpull.sh on EC2
      run: chmod +x dockerpull.sh
    - name: Run deploy.sh on EC2
      run: |
          ./dockerpull.sh     
    - name: Deploy to Server 1
      uses: easingthemes/ssh-deploy@main
      with:
        SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
        REMOTE_HOST: ${{ secrets.HOST_DNS }}
        REMOTE_USER: ${{ secrets.SERVER_USERNAME }}
        TARGET: ${{ secrets.TARGET_DIR }}
               
      